### ISSUE TITLE
Could not set WEEK_PROGRAM_POINTER

### ISSUE THREAD

**Issue by Havoc85** [danielperna84/pyhomematic#238]
I'm trying to set the WEEK_PROGRAM_POINTER, but I get the following messages:

```bash
2019-04-15 22:08:33 DEBUG (SyncWorker_11) [homeassistant.components.homematic] Calling putParamset: ip, 002018A99C2418, MASTER, {'WEEK_PROGRAM_POINTER': 2}
2019-04-15 22:08:33 DEBUG (SyncWorker_11) [pyhomematic._hm] ServerThread.putParamset: Exception: <Fault -3: 'Unknown Paramset: MASTER'>
```
or, without the "paramset_key":
```bash
2019-04-15 22:05:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1848270992] required key not provided @ data['paramset_key']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1118, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: required key not provided @ data['paramset_key']
```
I'm sending this JSON over Services from Homeassistant (Service: homematic.put_paramset):

```json
{
  "interface" : "ip",
  "address" : "002018A99C2418",
  "paramset_key":"MASTER",
  "paramset": {
    "WEEK_PROGRAM_POINTER":2
  }
}
```

This is HmIP-eTRV-B Device:
```
current_temperature: 22.4
min_temp: 4.5
max_temp: 30.5
temperature: 17
operation_mode: auto
operation_list: manual,auto,boost
battery: High
valve: 4
level: 0
mode: null
voltage: 3
id: 002018A99C2418
interface: ip
friendly_name: heizung-wc
supported_features: 129
```
I also tried to ask, if there is something wrong with my configuration:
https://community.home-assistant.io/t/how-to-configure-the-week-mode-from-homematic-hmip-etrv-b-devices/109005 - but I think the messages in the debug log are clear now. I'm currently running Homeassistant: 0.91.2.

**Comment by danielperna84** [comment]
Out of the top of my head I don't know why this is failing. My first guess is, that you have to include the channel with the address like `00112233:1`. Which channel the correct one is depends on the device.

**Comment by Havoc85** [comment]
Thank you for that suggestion. But now, I get another error:

```bash
2019-04-16 20:01:42 DEBUG (SyncWorker_12) [homeassistant.components.homematic] Calling putParamset: ip, 002018A99C2418:1, MASTER, {'WEEK_PROGRAM_POINTER': 2}
2019-04-16 20:01:42 DEBUG (Thread-3) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 002018A99C2418:0, value_key = CONFIG_PENDING, value = True
2019-04-16 20:01:42 INFO (Thread-3) [pyhomematic.devicetypes.generic] HMGeneric.event: address=002018A99C2418:0, interface_id=homeassistant-ip, key=CONFIG_PENDING, value=True
2019-04-16 20:01:42 DEBUG (Thread-3) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 002018A99C2418:0, value_key = CONFIG_PENDING, value = True
2019-04-16 20:01:42 INFO (Thread-3) [pyhomematic.devicetypes.generic] HMGeneric.event: address=002018A99C2418:0, interface_id=homeassistant-ip, key=CONFIG_PENDING, value=True
2019-04-16 20:01:42 DEBUG (SyncWorker_12) [pyhomematic._hm] ServerThread.putParamset: Exception: <Fault -5: 'Invalid parameter or value'>
2019-04-16 20:01:42 DEBUG (Thread-3) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 002018A99C2418:0, value_key = CONFIG_PENDING, value = False
2019-04-16 20:01:42 INFO (Thread-3) [pyhomematic.devicetypes.generic] HMGeneric.event: address=002018A99C2418:0, interface_id=homeassistant-ip, key=CONFIG_PENDING, value=False
2019-04-16 20:01:42 DEBUG (Thread-3) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 002018A99C2418:0, value_key = CONFIG_PENDING, value = False
2019-04-16 20:01:42 INFO (Thread-3) [pyhomematic.devicetypes.generic] HMGeneric.event: address=002018A99C2418:0, interface_id=homeassistant-ip, key=CONFIG_PENDING, value=False
```

I'm using this Service Data now for put_paramset:
```bash
{
  "interface" : "ip",
  "address" : "002018A99C2418:1",
  "paramset_key":"MASTER",
  "paramset": {
    "WEEK_PROGRAM_POINTER":2
  }
}
```

Any more Ideas?

**Comment by danielperna84** [comment]
Try
```
{
  "interface" : "ip",
  "address" : "002018A99C2418:1",
  "paramset_key":"MASTER",
  "paramset": '{"WEEK_PROGRAM_POINTER":2}'
}
```

That's how it's shown in the service description.

**Comment by Havoc85** [comment]
> Try
> 
> ```
> {
>   "interface" : "ip",
>   "address" : "002018A99C2418:1",
>   "paramset_key":"MASTER",
>   "paramset": '{"WEEK_PROGRAM_POINTER":2}'
> }
> ```
> That's how it's shown in the service description.

Sorry, with that, it's saying it is an invalid JSON.

I tried some variants, but I can't find a working one. Maybe I missed something, but - for example - "WEEK_PROGRAM_POINTER":"2" didn't work. Or putting your snippet in a script (also saying, it's Invalid).

**Comment by danielperna84** [comment]
@klada 
Maybe you can help here?

**Comment by klada** [comment]
@Havoc85 `put_paramset` exposes a part of the low-level Homematic API to Home Assistant. If you want to use it, you need to know which datapoints and parameters a particular HM device supports.

Are you sure that the HmIP-eTRV-B even has a `MASTER` paramset? The example from the Home Assistant documentation applies to one particular Homematic device (non-IP). It really is just an example. I am successfully using `put_paramset` to set the week program on my HM-TC-IT-WM-W-EU devices. I don't have any HM-IP devices for testing, so I am afraid I cannot really be helpful here.

You may want to ask your question on the Homematic forum, more precisely you need to know how to set the week program pointer through the XML-RPC API. That does not really have anything to do with pyhomematic or Home Assistant yet, you need to know the API call first.

If they cannot help you can try to interact with the XML-RPC API manually from a Python Shell:

```python
from xmlrpc.client import ServerProxy
ccu_ip_url="http://user:password@ccu2_hostname:2010"
proxy = ServerProxy(ccu_ip_url)
print(proxy.listDevices())
```

That would be the hard way though :)

PS: If you are interested in getting in touch with the HM-API, this is the spec:
https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM_XmlRpc_API.pdf

**Comment by klada** [comment]
@Havoc85 Another update from my side: You might want to have a look at [Homematic Manager](https://github.com/hobbyquaker/homematic-manager). It allows you to browse your devices, list paramsets and also set different parameters. It's still a tool for advanced users, but much easier than speaking XML-RPC from the command line ;)

If you can set the week program with Homematic Manager you could probably also adjust it with pyhomematic/Home Assistant. But it's up to you to find out the correct channels and paramsets for your particular device.

**Comment by danielperna84** [comment]
Closing this issue for now. After all the put paramset service is working for others. So it just seems to be a matter of the correct syntax, which probably has been solved after almost a year has passed.
