### ISSUE TITLE
Climate errors with Home Assistant

### ISSUE THREAD

**Issue by nicx** [danielperna84/pyhomematic#256]
With latest HA version 0.99.x and latest CCU Firmware 3.47.15.32 (in my case a virtualized Debmatic VM) I get these errors with climate devices:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 266, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 300, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 175, in state
    return self.hvac_mode
  File "/usr/src/homeassistant/homeassistant/components/homematic/climate.py", line 69, in hvac_mode
    if self.target_temperature <= self._hmdevice.OFF_VALUE + 0.5:
TypeError: '<=' not supported between instances of 'str' and 'float'
2019-09-10 16:16:36 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 266, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 300, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 175, in state
    return self.hvac_mode
  File "/usr/src/homeassistant/homeassistant/components/homematic/climate.py", line 69, in hvac_mode
    if self.target_temperature <= self._hmdevice.OFF_VALUE + 0.5:
TypeError: '<=' not supported between instances of 'str' and 'float'
2019-09-10 16:16:36 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 266, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 300, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 175, in state
    return self.hvac_mode
  File "/usr/src/homeassistant/homeassistant/components/homematic/climate.py", line 69, in hvac_mode
    if self.target_temperature <= self._hmdevice.OFF_VALUE + 0.5:
TypeError: '<=' not supported between instances of 'str' and 'float'
```

Is this pyhomematic related or HA related or even user related? :)

**Comment by danielperna84** [comment]
That's a change that has been made in the Home Assistant component, specifically the climate platform. It has to be fixed there. So the issue you have reopened there is the correct one.
