### ISSUE TITLE
error for HM-CC-TC when service climate.set_hvac_mode is set to OFF

### ISSUE THREAD

**Issue by jamesdeeen** [danielperna84/pyhomematic#358]
**Home Assistant version (if applicable):**
2020.12.7
0.118.3

callstack:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/homematic/climate.py:148
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:24:23 PM (3 occurrences)
Last logged: 5:26:49 PM

[139771418984256] %i format: a number is required, not NoneType
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 499, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 536, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 430, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/homematic/climate.py", line 148, in set_hvac_mode
    self._hmdevice.turnoff()
  File "/usr/local/lib/python3.8/site-packages/pyhomematic/devicetypes/thermostats.py", line 47, in turnoff
    self.writeNodeData("SET_TEMPERATURE", self.OFF_VALUE)
  File "/usr/local/lib/python3.8/site-packages/pyhomematic/devicetypes/generic.py", line 346, in writeNodeData
    return self._setNodeData(name, self.WRITENODE, data, channel)
  File "/usr/local/lib/python3.8/site-packages/pyhomematic/devicetypes/generic.py", line 363, in _setNodeData
    LOG.error("HMDevice.setNodeData: %s not found with value %s on %i" %
TypeError: %i format: a number is required, not NoneType

```

**Describe the bug**
when homeassistant service climate.set_hvac_mode is used with older wall thermostat HM-CC-TC
an error is thrown
TypeError: %i format: a number is required, not NoneType
reason is perhaps, that HM-CC-TC  does not understand SET_TEMPERATURE, but only SETPOINT

**Expected behavior**
temperature is set to minimum value (6°C)

**Additional context**
only applies to HM-CC-TC, not the newer HM-CC-RT-DN

**Comment by rbloehm** [comment]
I think the issue has at least 2 different underlying causes:

1.
The error logging in _setNodeData could handle the channel=None case more gracefully, so the error message would be more useful. Maybe we can just a %s instead of %i in line 363?
https://github.com/danielperna84/pyhomematic/blob/483e593d4ce29598b10dbccbe8c5b2b5fdab53d8/pyhomematic/devicetypes/generic.py#L351-L365

2.
The homematic component handles the automatic detection of the correct datapoint to use when setting the temperature ("SETPOINT" vs "SET_TEMPERATURE"):
https://github.com/home-assistant/core/blob/4ec81d4b6749932d3a998440972da0c554d264bb/homeassistant/components/homematic/climate.py#L185
`        self._state = next(iter(self._hmdevice.WRITENODE.keys()))`
and then uses it when setting the temperature:
https://github.com/home-assistant/core/blob/4ec81d4b6749932d3a998440972da0c554d264bb/homeassistant/components/homematic/climate.py#L133-L139
```
    def set_temperature(self, **kwargs):
        """Set new target temperature."""
        temperature = kwargs.get(ATTR_TEMPERATURE)
        if temperature is None:
            return None


        self._hmdevice.writeNodeData(self._state, float(temperature))
```
That's why regular setting of the temperature works in the homeassistant component. But it would not work using pyhomematic directly because SET_TEMPERATURE is hardcoded:
https://github.com/danielperna84/pyhomematic/blob/483e593d4ce29598b10dbccbe8c5b2b5fdab53d8/pyhomematic/devicetypes/thermostats.py#L36-L43
Same for the turnoff function that is called when setting HVAC_MODE_OFF:
https://github.com/danielperna84/pyhomematic/blob/483e593d4ce29598b10dbccbe8c5b2b5fdab53d8/pyhomematic/devicetypes/thermostats.py#L45-L47

I don't have a quick solution right now (for the 2nd issue), but I hope this helps in deciding how to go about resolving the issue. The code in the homeassistant component and pyhomematic for the thermostats is pretty duplicated (probably to fix an issue directly in the component that should have been fixed in pyhomematic), but let's see what the most pragmatic way is to tackle this ;-)

**Comment by danielperna84** [comment]
Should be fixed with the [new integration](https://github.com/danielperna84/custom_homematic).
